#!/usr/bin/env zsh


down() {
wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
int_volume=${volume##Volume: }
new_int_volume=$(( int_volume * 100 ))

case $new_int_volume in
  ???|??|?) true ;;
  *) new_int_volume="${new_int_volume:0:3}" ;;
esac


final_volume="${new_int_volume//.}"
echo $final_volume

dunstify -a "VOLUME" "Decreasing to Volume:$final_volume%" -h int:value:"$final_volume" -i audio-volume-low-symbolic -r 2593 -u normal
}

up() {
wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
int_volume=${volume##Volume: }
new_int_volume=$(( int_volume * 100 ))

case $new_int_volume in
  ???|??|?) true ;;
  *) new_int_volume="${new_int_volume:0:3}" ;;
esac


final_volume="${new_int_volume//.}"
echo $final_volume

dunstify -a "VOLUME" "Decreasing to Volume:$final_volume%" -h int:value:"$final_volume" -i audio-volume-low-symbolic -r 2593 -u normal 
}


#mute() {
#  wpctl set-mute @DEFAULT_SINK@ toggle
#  dunstify -a "VOLUME" "VOLUME" -i audio-volume-muted-symbolic -r 2593 -u normal
#}


sound() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
  dunstify -a "VOLUME" "Sound On" -i audio-volume-high-symbolic -r 2593 -u normal
else 
  pamixer -m
  dunstify -a "VOLUME" "Sound Off" -i audio-volume-muted-symbolic -r 2593 -u normal
fi
}


micro() {
  wpctl set-mute @DEFAULT_SOURCE@ toggle
  dunstify -a "VOLUME" "Micro" -i audio-volume-muted-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
  sound) sound;;
  micro) micro;;
esac



