# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {

# ██╗  ██╗ █████╗ ██████╗ ██████╗ ██╗    ██╗ █████╗ ██████╗ ███████╗    ██╗    ██╗██╗███████╗████████╗███████╗██████╗ ██╗ █████╗ 
# ██║  ██║██╔══██╗██╔══██╗██╔══██╗██║    ██║██╔══██╗██╔══██╗██╔════╝    ██║    ██║██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗██║██╔══██╗
# ███████║███████║██████╔╝██║  ██║██║ █╗ ██║███████║██████╔╝█████╗      ██║ █╗ ██║██║███████╗   ██║   █████╗  ██████╔╝██║███████║
# ██╔══██║██╔══██║██╔══██╗██║  ██║██║███╗██║██╔══██║██╔══██╗██╔══╝      ██║███╗██║██║╚════██║   ██║   ██╔══╝  ██╔══██╗██║██╔══██║
# ██║  ██║██║  ██║██║  ██║██████╔╝╚███╔███╔╝██║  ██║██║  ██║███████╗    ╚███╔███╔╝██║███████║   ██║   ███████╗██║  ██║██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝     ╚══╝╚══╝ ╚═╝╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝

  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration.
  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    extraModulePackages = [ ];
    kernelModules = [  ];
    supportedFilesystems = [ "ntfs" ];
  };

  # Enable nested virsualization, required by security containers and nested vm.
  # This should be set per host in /hosts, not here.
  #
  ## For AMD CPU, add "kvm-amd" to kernelModules.
  # boot.kernelModules = ["kvm-amd"];
  # boot.extraModprobeConfig = "options kvm_amd nested=1";  # For amd cpu.
  #
  ## For Intel CPU, add "kvm-intel" to kernelModules.
  # boot.kernelModules = ["kvm-intel"];
  # boot.extraModprobeConfig = "options kvm_intel nested=1"; # For intel cpu.


# ███╗   ███╗ ██████╗ ██╗   ██╗███╗   ██╗████████╗███████╗
# ████╗ ████║██╔═══██╗██║   ██║████╗  ██║╚══██╔══╝██╔════╝
# ██╔████╔██║██║   ██║██║   ██║██╔██╗ ██║   ██║   ███████╗
# ██║╚██╔╝██║██║   ██║██║   ██║██║╚██╗██║   ██║   ╚════██║
# ██║ ╚═╝ ██║╚██████╔╝╚██████╔╝██║ ╚████║   ██║   ███████║
# ╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚══════╝
  # boot.
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CF4-2AC6";
      fsType = "vfat";
    };

  # nvme 500GB.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e71170a2-c919-4bb9-9f29-e5852c503134";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    }; 

  #fileSystems."/path/to/ssd" = 
   # { device = "/dev/disk/by-uuid/A43C2CD13C2CA072";
    #  fsType = "ntfs";
    #};

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0f4u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
